### ISSUE TITLE
Extension breaks Okta sign-in to GHE

### ISSUE THREAD

**Issue by maksimov** [jessejanderson/skylink#26]
I have observed it in both Chrome and Arc, after installing the extension my Okta redirects to GitHub Enterprise have stopped working: GHE would say they couldn't authenticate with my SAML provider. Disabling the extension fixed the issue immediately. 
I don't know if the extension is messing up the headers (I'd be surprised) or the redirect URL, but it would appear so.

Unfortunately this report isn't too technical, but let me know if any further details would be helpful.

**Comment by sanitybit** [comment]
A cursory think-over, the only thing that comes to mind here is maybe a CSP policy issue that's tied to looking up the DID over HTTPS, however I haven't been able to replicate this with Okta and GitHub enterprise. 

Is your GHE instance hosted at github.com, or is it an internal instance? I can only test with the former.

**Comment by maksimov** [comment]
Our GHE is self-hosted

**Comment by sanitybit** [comment]
I think I have a version that will fix this. I have to test that everything is also working in Firefox, then I'll get it in front of Jesse for review.

**Comment by sanitybit** [comment]
@maksimov Version 1.4.0 should fix this issue. It's currently awaiting review prior to being published in the Chrome web store.

**Comment by jessejanderson** [comment]
@maksimov 1.4.0 is out now, please let us know if this issue is resolved!

**Comment by maksimov** [comment]
I think it works now. I had it on for three days and didn't have any issues. Thank you!
